import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  metadataBase: new URL("https://storeagent.kr"),
  title: "STOREAGENT - 편의점 점주를 위한 AI 브리핑",
  description: "발주 전 3분, 확인하고 가세요. 날씨, 이벤트, 오늘 체크할 것들을 매일 아침 정리해 드립니다. 본사 연동 없이 바로 시작하세요.",
  keywords: ["편의점", "점주", "모닝브리핑", "AI", "발주", "스토어에이전트"],
  authors: [{ name: "STOREAGENT" }],
  icons: {
    icon: [
      { url: "/icon.svg", type: "image/svg+xml" },
    ],
    apple: "/icon.svg",
  },
  openGraph: {
    title: "STOREAGENT - 편의점 점주를 위한 AI 브리핑",
    description: "발주 전 3분, 확인하고 가세요. 날씨, 이벤트, 오늘 체크할 것들을 매일 아침 정리해 드립니다.",
    url: "https://storeagent.kr",
    siteName: "STOREAGENT",
    locale: "ko_KR",
    type: "website",
    // OG image is auto-generated by opengraph-image.tsx
  },
  twitter: {
    card: "summary_large_image",
    title: "STOREAGENT - 편의점 점주를 위한 AI 브리핑",
    description: "발주 전 3분, 확인하고 가세요.",
    // Twitter image is auto-generated by twitter-image.tsx
  },
  robots: {
    index: true,
    follow: true,
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        <main className="pt-16">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
